spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/CurrencyRates
    username: postgres
    password: zaq1@WSX
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  servlet:
    context-path: "/currencyRates"

bank:
  nbp:
    url: "http://api.nbp.pl/api/exchangerates/tables/a"